mqtt:
  binary_sensor:
    # --- Kiryat Haim immediate ---
    - name: Missile Alert - Kiryat Haim
      state_topic:           "missile_alerts/5001878"
      json_attributes_topic: "missile_alerts/5001878_attr"
      payload_on:  "1"
      payload_off: "0"
      value_template: "{{ value|default('0') }}"
      device_class: safety
      off_delay: 600

    # --- Kiryat Motzkin immediate ---
    - name: Missile Alert - Kiryat Motzkin
      state_topic:           "missile_alerts/5001347"
      json_attributes_topic: "missile_alerts/5001347_attr"
      payload_on:  "1"
      payload_off: "0"
      value_template: "{{ value|default('0') }}"
      device_class: safety
      off_delay: 600